            /** @param {string} mineral, @param {string} remove_or_fill **/
var mineralStatus = function(mineral, remove_or_fill){
    "H": remove_or_fill,
    "O": remove_or_fill,
    "U": remove_or_fill,
    "L": remove_or_fill,
    "K": remove_or_fill,
    "Z": remove_or_fill,
    "X": remove_or_fill,
    "G": remove_or_fill,

    "OH": remove_or_fill,
    "ZK": remove_or_fill,
    "UL": remove_or_fill,

    "UH": remove_or_fill,
    "UO": remove_or_fill,
    "KH": remove_or_fill,
    "KO": remove_or_fill,
    "LH": remove_or_fill,
    "LO": remove_or_fill,
    "ZH": remove_or_fill,
    "ZO": remove_or_fill,
    "GH": remove_or_fill,
    "GO": remove_or_fill,

    "UH2O": remove_or_fill,
    "UHO2": remove_or_fill,
    "KH2O": remove_or_fill,
    "KHO2": remove_or_fill,
    "LH2O": remove_or_fill,
    "LHO2": remove_or_fill,
    "ZH2O": remove_or_fill,
    "ZHO2": remove_or_fill,
    "GH2O": remove_or_fill,
    "GHO2": remove_or_fill,

    "XUH2O": remove_or_fill,
    "XUHO2": remove_or_fill,
    "XKH2O": remove_or_fill,
    "XKHO2": remove_or_fill,
    "XLH2O": remove_or_fill,
    "XLHO2": remove_or_fill,
    "XZH2O": remove_or_fill,
    "XZHO2": remove_or_fill,
    "XGH2O": remove_or_fill,
    "XGHO2": remove_or_fill,
};
